version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network

  prestashop:
    image: prestashop/prestashop:8
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin1234
      PS_FOLDER_INSTALL: install1234
      PS_COUNTRY: ES
      PS_LANGUAGE: es
      PS_DEV_MODE: 1
    volumes:
      - ./prestashop:/var/www/html
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  db_data: 